consider new and old server URL when checking for project server (fix #409)
lutraconsulting/qgis-mergin-plugin pull request #420
Opened 2022-06-06 12:21 UTC by alexbruy

Validate project URL against new and old server URL before syncing.

Fixes #409.

2022-06-06 16:09 UTC, PeterPetrik approved these changes

2022-06-07 05:37 UTC, varmar05 requested changes

2022-06-07 05:37 UTC, varmar05 commented on Mergin/projects_manager.py
> +            elif project_url.netloc.startswith("public.cloudmergin") or url.netloc.startswith("app.merginmaps"):
what is `project_url`?

2022-06-07 06:10 UTC, varmar05 approved these changes

2022-06-07 06:11 UTC, merged